import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  titulo:{
    fontSize:24,
    fontStyle:'italic',
    color:'#fff',
    margin:5,
    marginBottom:10,
  },
  imagenes:{
    height:240,
    width:300,
    marginBottom:5
  },  
  viewimagenes:{
    marginRight:10,
    marginLeft:5,
  },  
  banner:{
    height:300,
    width:'100%',
    marginHorizontal:5,    
  },
  tituloSeries:{
    fontSize:16,
    fontStyle:'italic',
    color:'#fff',    
    paddingHorizontal:10,
  },
  tituloVideosProximamente:{
    fontSize:14,
    fontStyle:'bold',
    color:'#fff',    
    paddingHorizontal:10,
    marginVertical:10,
  },
  maxtituloVideosProximamente:{
    fontSize:24,    
    fontStyle:'bold',    
    color:'#fff',
    alignSelf:'center',    
  },
  viewimagenesSeries:{
    marginRight:15,
    marginLeft:5,
    flexDirection:'row',
  },
  viewVideosProximamente:{
    marginRight:15,
    marginLeft:5,
    flexDirection:'column',
  },
  subviewimagenesSeries:{    
    flexDirection:'column',
    flex:1,
  },
  imagenesSeries:{
    height:120,
    width:150,
    marginBottom:10,
    borderWidth:1,
    borderColor:'red', 
  },  
    botoncerrar:{
    position:'absolute',
    top:10,
    right:10,   
    marginBottom:30, 
    zIndex:1,
  },
video:{    
    width:360,
    height:250,       
    alignSelf:'center',    
  },
  modal:{        
    alignContent:'center',
  },  
  fondo:{    
    flexDirection:'column',
    alignSelf:'center',
    marginTop:'50%',
    backgroundColor:'#000',    
  },
  titulo2:{
    color:"#fff",    
    fontSize:20,
    marginTop:5,    
    paddingHorizontal:40,
    textAlign:'center',
  },
  subcontenedor:{
    flexDirection:'column',    
  },
  videoProximamente:{    
    width:360,
    height:250,       
    alignSelf:'center',
    borderWidth:2,
    borderColor:'gold',
  },
})